"""new fields in user model

Revision ID: 84edc640f4f9
Revises: e42178bf740f
Create Date: 2022-01-31 10:39:24.161695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84edc640f4f9'
down_revision = 'e42178bf740f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about')
    # ### end Alembic commands ###
