"""followers

Revision ID: 98adc407607d
Revises: 74fd72b7f036
Create Date: 2022-02-01 19:29:41.182525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98adc407607d'
down_revision = '74fd72b7f036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('followed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'followers', 'user', ['followed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_column('followers', 'followed_id')
    # ### end Alembic commands ###
